# Generated by Django 4.0.5 on 2022-07-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='imagen',
            field=models.ImageField(blank=True, db_column='Imagen', null=True, upload_to=''),
        ),
    ]
