# Generated by Django 3.2.14 on 2022-08-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0002_alter_muser_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipersona',
            name='foto',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to=''),
        ),
    ]
