# Generated by Django 3.2.14 on 2022-08-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0003_alter_ipersona_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpenales',
            name='fechamodifica',
            field=models.DateTimeField(auto_now=True, db_column='FechaModifica', null=True),
        ),
    ]
