# Generated by Django 3.2.14 on 2022-08-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0004_alter_rpenales_fechamodifica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpenales',
            name='fechacrea',
            field=models.DateTimeField(auto_now_add=True, db_column='FechaCrea', null=True),
        ),
    ]
