# Generated by Django 3.2.14 on 2022-08-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0005_alter_rpenales_fechacrea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipersona',
            name='foto',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='IPersona'),
        ),
        migrations.AlterField(
            model_name='rfamiliares',
            name='fechacrea',
            field=models.DateTimeField(auto_now_add=True, db_column='FechaCrea', null=True),
        ),
        migrations.AlterField(
            model_name='rfamiliares',
            name='fechamodifica',
            field=models.DateTimeField(auto_now=True, db_column='FechaModifica', null=True),
        ),
        migrations.AlterField(
            model_name='tipoffaa',
            name='fechacrea',
            field=models.DateTimeField(auto_now_add=True, db_column='FechaCrea', null=True),
        ),
        migrations.AlterField(
            model_name='tipoffaa',
            name='fechamodifica',
            field=models.DateTimeField(auto_now=True, db_column='FechaModifica', null=True),
        ),
    ]
