# Generated by Django 3.2.14 on 2022-09-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0006_auto_20220809_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iffaa',
            name='fechacrea',
            field=models.DateTimeField(auto_now_add=True, db_column='FechaCrea', null=True),
        ),
        migrations.AlterField(
            model_name='iffaa',
            name='fechamodifica',
            field=models.DateTimeField(auto_now=True, db_column='FechaModifica', null=True),
        ),
        migrations.AlterField(
            model_name='ipersona',
            name='foto',
            field=models.ImageField(blank=True, db_column='Foto', default='logo.png', null=True, upload_to='IPersona'),
        ),
        migrations.AlterField(
            model_name='ipolicia',
            name='fechacrea',
            field=models.DateTimeField(auto_now_add=True, db_column='FechaCrea', null=True),
        ),
        migrations.AlterField(
            model_name='ipolicia',
            name='fechamodifica',
            field=models.DateTimeField(auto_now=True, db_column='FechaModifica', null=True),
        ),
        migrations.AlterField(
            model_name='msitpolicial',
            name='fechacrea',
            field=models.DateTimeField(auto_now_add=True, db_column='FechaCrea', null=True),
        ),
        migrations.AlterField(
            model_name='msitpolicial',
            name='fechamodifica',
            field=models.DateTimeField(auto_now=True, db_column='FechaModifica', null=True),
        ),
        migrations.AlterField(
            model_name='rfiliacionpolitica',
            name='fechacrea',
            field=models.DateTimeField(auto_now_add=True, db_column='FechaCrea', null=True),
        ),
        migrations.AlterField(
            model_name='rfiliacionpolitica',
            name='fechamodifica',
            field=models.DateTimeField(auto_now=True, db_column='FechaModifica', null=True),
        ),
        migrations.AlterField(
            model_name='tipoffaa',
            name='fechacrea',
            field=models.DateTimeField(blank=True, db_column='FechaCrea', null=True),
        ),
        migrations.AlterField(
            model_name='tipoffaa',
            name='fechamodifica',
            field=models.DateTimeField(blank=True, db_column='FechaModifica', null=True),
        ),
    ]
